In [32]:
import tensorflow as tf
from tensorflow.keras.layers import Input, SimpleRNN, Dense, Flatten
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import SGD, Adam

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [33]:
# N = number of samples
# T = sequence length
# D = number of input features
# M = number of hidden units
# K = number of output units 

In [34]:
N = 10
T = 10
D = 3
K = 2
X = np.random.randn(N, T, D)

In [35]:
M = 5
i = Input(shape=(T, D))
x = SimpleRNN(M)(i)
x = Dense(K)(x)

model = Model(i, x)

In [36]:
yhat = model.predict(X)
print(yhat)

1/1 [==============================] - 0s 135ms/step
[[-0.01208027  0.57277954]
 [ 0.08566242 -0.446132  ]
 [ 0.14154996 -0.35068968]
 [ 0.2627417  -0.25875467]
 [-0.44178686  0.22801803]
 [ 0.36954817  0.4384649 ]
 [ 0.7108621  -1.2339133 ]
 [ 0.84398556 -1.0795323 ]
 [ 0.3515938  -0.6782257 ]
 [-0.6044412   0.87560403]]


In [37]:
model.summary()

Model: "model_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_3 (InputLayer)        [(None, 10, 3)]           0         
                                                                 
 simple_rnn_2 (SimpleRNN)    (None, 5)                 45        
                                                                 
 dense_2 (Dense)             (None, 2)                 12        
                                                                 
Total params: 57
Trainable params: 57
Non-trainable params: 0
_________________________________________________________________


In [38]:
model.layers[1].get_weights()

[array([[-0.3951038 ,  0.27778178, -0.10952711,  0.35174888,  0.55116004],
        [ 0.67333657, -0.24542421,  0.12940627,  0.18594247,  0.44220442],
        [ 0.5559065 , -0.4200146 ,  0.15774173, -0.17144513, -0.18284404]],
       dtype=float32),
 array([[ 0.44516814,  0.6051888 , -0.1139871 ,  0.04167719,  0.6487233 ],
        [-0.2899032 ,  0.05763198, -0.36798385,  0.88127834,  0.02389753],
        [ 0.24905716,  0.5717816 , -0.23770726, -0.03454782, -0.743867  ],
        [-0.77375203,  0.39075568, -0.26688045, -0.39545354,  0.14494506],
        [-0.23887193,  0.38833106,  0.8508025 ,  0.25305018, -0.0651145 ]],
       dtype=float32),
 array([0., 0., 0., 0., 0.], dtype=float32)]

In [39]:
model.layers

In [40]:
a, b, c = model.layers[1].get_weights()
print(a.shape, b.shape, c.shape)

(3, 5) (5, 5) (5,)


In [41]:
Wx, Wh, bh = model.layers[1].get_weights()
Wo, bo = model.layers[2].get_weights()

In [44]:
Yhats = [] # Store the outputs

for x in X:
  h_last = np.zeros(M) # initial hidden state
  for t in range(T):
    h = np.tanh(x[t].dot(Wx) + h_last.dot(Wh) + bh)
    h_last = h # update hidden RNN unit
  y = h_last.dot(Wo) + bo # Only this value is important in the last iteration
  Yhats.append(y)

print(Yhats) # print the final output
print(np.allclose(Yhats, yhat))

[array([-0.01208028,  0.57277955]), array([ 0.08566242, -0.44613215]), array([ 0.14154992, -0.35068971]), array([ 0.26274176, -0.25875458]), array([-0.44178683,  0.22801797]), array([0.36954808, 0.43846491]), array([ 0.71086201, -1.23391315]), array([ 0.84398552, -1.07953215]), array([ 0.35159378, -0.67822563]), array([-0.60444117,  0.87560402])]
True
